import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.57.4";
const origins=new Set(["https://maxwell196909.github.io","https://echocity.org","https://www.echocity.org","https://maxwellchengresearch.com","https://www.maxwellchengresearch.com"]);
function cors(o:string|null){const a=o&&origins.has(o)?o:"https://maxwell196909.github.io";return{"Access-Control-Allow-Origin":a,"Access-Control-Allow-Headers":"authorization,x-client-info,apikey,content-type","Access-Control-Allow-Methods":"POST,OPTIONS","Vary":"Origin"}}
function out(v:unknown,s:number,o:string|null){return new Response(JSON.stringify(v),{status:s,headers:{...cors(o),"Content-Type":"application/json"}})}
Deno.serve(async(req:Request)=>{const origin=req.headers.get("origin");if(req.method==="OPTIONS")return new Response("ok",{headers:cors(origin)});if(req.method!=="POST")return out({error:"METHOD_NOT_ALLOWED"},405,origin);if(origin&&!origins.has(origin))return out({error:"ORIGIN_NOT_ALLOWED"},403,origin);
 try{const b=await req.json(),requestNo=String(b.requestNo||"").trim().toUpperCase(),token=String(b.token||"").trim(),caseNo=String(b.caseNo||"").trim(),actorRole=String(b.actorRole||"customer");if(!/^REQ-[A-Z0-9-]{4,80}$/.test(requestNo)||token.length!==64||!/^AS-[A-Z0-9-]{8,40}$/.test(caseNo)||!["customer","worker","platform"].includes(actorRole))return out({error:"INVALID_REQUEST"},400,origin);
 const url=Deno.env.get("SUPABASE_URL"),key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!url||!key)return out({error:"SERVER_CONFIG_ERROR"},500,origin);const admin=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});
 let valid=false;if(actorRole==="platform"){const x=await admin.rpc("get_platform_after_sales_evidence_with_token",{p_platform_token:token});valid=!x.error}else{const x=await admin.rpc("validate_task_access_token",{p_request_no:requestNo,p_role:actorRole,p_token:token});valid=x.data===true}if(!valid)return out({error:"ACCESS_LINK_EXPIRED_OR_INVALID"},403,origin);
 const {data:c}=await admin.from("after_sales_cases").select("id,case_no,request_no,status,responsible_worker_phone").eq("case_no",caseNo).eq("request_no",requestNo).single();if(!c)return out({error:"AFTER_SALES_CASE_NOT_FOUND"},404,origin);if(actorRole==="worker"){const {data:r}=await admin.from("service_requests").select("assigned_worker_phone").eq("request_no",requestNo).single();const digits=(v:unknown)=>String(v||"").replace(/\D/g,"");if(!r||!digits(c.responsible_worker_phone)||digits(c.responsible_worker_phone)!==digits(r.assigned_worker_phone))return out({error:"REMEDIATION_NOT_ASSIGNED_TO_WORKER"},403,origin)}
 if(String(b.action||"upload")==="view"){const evidenceId=String(b.evidenceId||"");const {data:e}=await admin.from("after_sales_evidence").select("id,bucket_id,storage_path,uploaded_by_role,review_status").eq("id",evidenceId).eq("case_id",c.id).single();if(!e||(actorRole==="worker"&&e.uploaded_by_role!=="worker"&&e.review_status!=="accepted"))return out({error:"EVIDENCE_NOT_FOUND"},404,origin);const {data:signed,error}=await admin.storage.from(e.bucket_id).createSignedUrl(e.storage_path,600);if(error||!signed?.signedUrl)return out({error:"SIGNED_VIEW_FAILED"},500,origin);return out({signedUrl:signed.signedUrl,expiresIn:600},200,origin)}
 if(!["customer","worker"].includes(actorRole))return out({error:"ROLE_CANNOT_UPLOAD"},403,origin);
 if(["closed","rejected"].includes(c.status)||(actorRole==="worker"&&c.status!=="repairing"))return out({error:"CASE_NOT_OPEN_FOR_EVIDENCE"},409,origin);const fileName=String(b.fileName||"").slice(0,180),mime=String(b.mimeType||"").toLowerCase(),size=Number(b.fileSize||0),types:Record<string,string>={"image/jpeg":"jpg","image/png":"png","image/heic":"heic","video/mp4":"mp4","video/quicktime":"mov"};const limit=mime.startsWith("image/")?15728640:104857600;if(!types[mime]||!Number.isSafeInteger(size)||size<1||size>limit)return out({error:"INVALID_EVIDENCE_FILE"},400,origin);const path=`${requestNo}/${actorRole}/after-sales/${caseNo}/${Date.now()}-${crypto.randomUUID()}.${types[mime]}`;const {data:signed,error}=await admin.storage.from("work-evidence").createSignedUploadUrl(path,{upsert:false});if(error||!signed?.token)return out({error:"SIGNED_UPLOAD_FAILED"},500,origin);return out({bucket:"work-evidence",path,uploadToken:signed.token,maxFileBytes:limit,originalFileName:fileName},200,origin)
 }catch(e){console.error(e);return out({error:"UNEXPECTED_ERROR"},500,origin)}});
