create or replace function public.get_platform_order_360_with_token(p_request_no text,p_token text)
returns jsonb language plpgsql stable security definer set search_path=''
as $$
declare v_no text:=upper(trim(p_request_no)); r public.service_requests;
begin
  if p_token is null or length(p_token)<64 or length(p_token)>128 then raise exception 'INVALID_PLATFORM_LINK'; end if;
  if not exists(select 1 from private.platform_dashboard_tokens t where t.token_hash=encode(extensions.digest(p_token,'sha256'),'hex') and t.revoked_at is null and t.expires_at>now()) then raise exception 'PLATFORM_LINK_EXPIRED_OR_INVALID'; end if;
  select * into r from public.service_requests where request_no=v_no;if r.id is null then raise exception 'REQUEST_NOT_FOUND'; end if;
  return jsonb_build_object(
    'request',jsonb_build_object('request_no',r.request_no,'service_type',r.service_type,'description',r.description,'status',r.status,'current_actor',r.current_actor,'next_action',r.next_action,'risk_level',r.risk_level,'customer_name',r.customer_name,'customer_phone',r.customer_phone,'address',r.address,'quote_amount',r.quote_amount,'assigned_worker',r.assigned_worker,'assigned_worker_phone',r.assigned_worker_phone,'work_started_at',r.work_started_at,'work_completed_at',r.work_completed_at,'final_acceptance_status',r.final_acceptance_status,'updated_at',r.updated_at),
    'worker',(select jsonb_build_object('id',w.id,'name',w.full_name,'phone',w.phone,'status',w.status,'verification',w.verification_status,'availability',w.availability_status,'credit_score',w.credit_score,'completed_orders',w.completed_orders,'rework_count',w.rework_count,'dispute_count',w.dispute_count) from public.service_workers w where regexp_replace(w.phone,'\D','','g')=regexp_replace(coalesce(r.assigned_worker_phone,''),'\D','','g') limit 1),
    'plan',(select jsonb_build_object('id',p.id,'version',p.version,'status',p.status,'platform_approval',p.platform_approval_status,'customer_confirmed_at',p.customer_confirmed_at,'prestart_ready',p.prestart_ready,'approval_note',p.approval_note,'content',p.content,'updated_at',p.updated_at) from public.implementation_plans p where p.request_no=v_no order by p.version desc limit 1),
    'work',jsonb_build_object('record_count',(select count(*) from public.work_records w where w.request_no=v_no),'hours',(select coalesce(sum(w.work_hours),0) from public.work_records w where w.request_no=v_no),'photo_count',(select count(*) from public.work_records w where w.request_no=v_no and nullif(trim(w.photo_record),'') is not null),'video_count',(select count(*) from public.work_records w where w.request_no=v_no and nullif(trim(w.video_record),'') is not null),'latest',(select jsonb_build_object('progress',w.work_progress,'materials',w.materials_used,'issues',w.issues_found,'recorded_at',w.recorded_at) from public.work_records w where w.request_no=v_no order by w.recorded_at desc limit 1)),
    'quality',jsonb_build_object('milestone_summary',r.milestone_summary,'milestone_submitted_at',r.milestone_submitted_at,'completion_summary',r.completion_summary,'outstanding_issues',r.outstanding_issues,'final_status',r.final_acceptance_status,'final_data',r.final_acceptance_data),
    'settlement',(select jsonb_build_object('status',s.status,'total_amount',s.total_amount,'worker_amount',s.worker_amount,'platform_fee',s.platform_fee,'currency',s.currency,'customer_paid_at',s.customer_paid_at,'worker_received_at',s.worker_received_at,'archived_at',s.archived_at) from public.order_settlements s where s.request_no=v_no order by s.updated_at desc limit 1),
    'warranty',(select jsonb_build_object('id',w.id,'status',w.status,'start_at',w.warranty_start_at,'end_at',w.warranty_end_at,'scope',w.coverage_scope,'exclusions',w.exclusions,'response_hours',w.response_hours) from public.warranty_records w where w.request_no=v_no),
    'after_sales',jsonb_build_object('open_count',(select count(*) from public.after_sales_cases c where c.request_no=v_no and c.status not in ('closed','rejected')),'evidence_count',(select count(*) from public.after_sales_evidence e where e.request_no=v_no),'cases',coalesce((select jsonb_agg(jsonb_build_object('case_no',c.case_no,'status',c.status,'severity',c.severity,'issue',c.issue_description,'due_at',c.due_at,'customer_result',c.customer_reinspection_result) order by c.opened_at desc) from public.after_sales_cases c where c.request_no=v_no),'[]'::jsonb)),
    'incidents',coalesce((select jsonb_agg(jsonb_build_object('id',i.id,'type',i.incident_type,'severity',i.severity,'status',i.status,'title',i.title,'detail',i.detail,'updated_at',i.updated_at) order by i.updated_at desc) from public.platform_incidents i where i.request_no=v_no),'[]'::jsonb),
    'timeline',coalesce((select jsonb_agg(x order by (x->>'time')::timestamptz) from (
      select jsonb_build_object('time',e.created_at,'source','task_event','title',e.action,'status',e.to_status,'actor',e.actor_role,'note',e.note) x from public.task_events e where e.request_no=v_no
      union all select jsonb_build_object('time',e.event_time,'source',e.event_source,'title',e.title,'status',null,'actor',e.actor_role,'note',e.description) from public.task_timeline_events e where e.request_no=v_no
      union all select jsonb_build_object('time',e.created_at,'source','after_sales','title',e.action,'status',e.to_status,'actor',e.actor_role,'note',e.note) from public.after_sales_events e where e.request_no=v_no
    ) z),'[]'::jsonb)
  );
end;$$;
revoke all on function public.get_platform_order_360_with_token(text,text) from public;
grant execute on function public.get_platform_order_360_with_token(text,text) to anon,authenticated,service_role;
